import React, { useState, useCallback, useEffect } from 'react';
import { useToast } from '../../../../hooks/utils/useToast';
import { usePaymentProviderAccounts } from '../../../../hooks/api/usePaymentProviderAccounts';
import { usePaymentProviders } from '../../../../hooks/api/usePaymentProviders';
import { Search, Plus, Edit2, Trash2, CheckCircle, AlertCircle, Wallet, Save, X, Eye, EyeOff, Building2 } from 'lucide-react';
import AdminPageLayout from '../../../../components/AdminPageLayout';

const PaymentProviderAccounts = () => {
  const { toast, showToast } = useToast();
  const { paymentProviderAccounts, loading: accountsLoading, fetchPaymentProviderAccounts, createPaymentProviderAccount, updatePaymentProviderAccount, deletePaymentProviderAccount } = usePaymentProviderAccounts();
  const { paymentProviders, loading: providersLoading, fetchPaymentProviders } = usePaymentProviders();
  const [searchTerm, setSearchTerm] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingAccount, setEditingAccount] = useState(null);
  const [showSecretKey, setShowSecretKey] = useState(false);
  const [formData, setFormData] = useState({ paymentProviderId: '', accountName: '', publishableKey: '', secretKey: '', isActiveForPayment: 0, isTestMode: 0 });
  const [submitting, setSubmitting] = useState(false);

  const filteredAccounts = paymentProviderAccounts.filter(account => account.accountName?.toLowerCase().includes(searchTerm.toLowerCase()) || account.paymentProviderTitle?.toLowerCase().includes(searchTerm.toLowerCase()));

  const handleCreate = useCallback(() => { setEditingAccount(null); setShowSecretKey(false); setFormData({ paymentProviderId: '', accountName: '', publishableKey: '', secretKey: '', isActiveForPayment: 0, isTestMode: 0 }); setShowModal(true); }, []);
  const handleEdit = useCallback((account) => { setEditingAccount(account); setShowSecretKey(false); setFormData({ paymentProviderId: account.paymentProviderId?.toString() || '', accountName: account.accountName || '', publishableKey: account.publishableKey || '', secretKey: account.secretKey || '', isActiveForPayment: account.isActiveForPayment || 0, isTestMode: account.isTestMode || 0 }); setShowModal(true); }, []);
  const handleDelete = useCallback(async (account) => { if (window.confirm(`Delete "${account.accountName}"?`)) { try { await deletePaymentProviderAccount(account.id); showToast('Deleted successfully', 'success'); } catch (error) { showToast('Failed to delete', 'error'); } } }, [deletePaymentProviderAccount, showToast]);
  const handleSubmit = useCallback(async (e) => { e.preventDefault(); if (!formData.accountName.trim() || !formData.paymentProviderId || !formData.publishableKey.trim() || !formData.secretKey.trim()) { showToast('All fields are required', 'error'); return; } setSubmitting(true); try { const userId = localStorage.getItem('userId') || 0; const payload = { paymentProviderId: parseInt(formData.paymentProviderId), accountName: formData.accountName, publishableKey: formData.publishableKey, secretKey: formData.secretKey, isActiveForPayment: formData.isActiveForPayment ? 1 : 0, isTestMode: formData.isTestMode ? 1 : 0, createdBy: userId }; if (editingAccount) { await updatePaymentProviderAccount(editingAccount.id, payload); showToast('Updated successfully', 'success'); } else { await createPaymentProviderAccount(payload); showToast('Created successfully', 'success'); } setShowModal(false); setEditingAccount(null); setFormData({ paymentProviderId: '', accountName: '', publishableKey: '', secretKey: '', isActiveForPayment: 0, isTestMode: 0 }); } catch (error) { showToast('Failed to save', 'error'); } finally { setSubmitting(false); } }, [formData, editingAccount, updatePaymentProviderAccount, createPaymentProviderAccount, showToast]);

  useEffect(() => { fetchPaymentProviderAccounts(); fetchPaymentProviders(); }, [fetchPaymentProviderAccounts, fetchPaymentProviders]);

  return (
    <AdminPageLayout title="Payment Provider Accounts" subtitle="Manage accounts with API keys" icon={Wallet} loading={accountsLoading || providersLoading} actions={<button onClick={handleCreate} className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"><Plus className="w-4 h-4 mr-2" />Create Account</button>}>
      {toast.show && <div className={`fixed top-4 right-4 z-50 px-6 py-3 rounded-lg shadow-lg ${toast.type === 'success' ? 'bg-green-500 text-white' : 'bg-red-500 text-white'}`}><div className="flex items-center space-x-2">{toast.type === 'success' ? <CheckCircle className="w-5 h-5" /> : <AlertCircle className="w-5 h-5" />}<span className="font-medium">{toast.message}</span></div></div>}
      <div className="mb-6"><div className="relative"><Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" /><input type="text" placeholder="Search accounts..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" /></div></div>
      <div className="bg-white rounded-lg shadow-sm border border-gray-200">
        {filteredAccounts.length > 0 ? (
          <div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Account Name</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Provider</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Mode</th><th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th><th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th></tr></thead><tbody className="bg-white divide-y divide-gray-200">{filteredAccounts.map((account) => (<tr key={account.id} className="hover:bg-gray-50"><td className="px-4 py-4 whitespace-nowrap text-sm text-gray-500">#{account.id}</td><td className="px-4 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><div className="flex items-center"><Wallet className="w-4 h-4 text-blue-600 mr-2" />{account.accountName}</div></td><td className="px-4 py-4 whitespace-nowrap text-sm text-gray-700"><div className="flex items-center"><Building2 className="w-4 h-4 text-gray-400 mr-2" />{account.paymentProviderTitle || 'Unknown'}</div></td><td className="px-4 py-4 whitespace-nowrap text-sm"><span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${account.isTestMode ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800'}`}>{account.isTestMode ? 'Test' : 'Live'}</span></td><td className="px-4 py-4 whitespace-nowrap text-sm"><span className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${account.isActiveForPayment ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>{account.isActiveForPayment ? 'Active' : 'Inactive'}</span></td><td className="px-4 py-4 whitespace-nowrap text-sm text-right"><div className="flex items-center justify-end space-x-2"><button onClick={() => handleEdit(account)} className="text-blue-600 hover:bg-blue-50 p-2 rounded-md"><Edit2 className="w-4 h-4" /></button><button onClick={() => handleDelete(account)} className="text-red-600 hover:bg-red-50 p-2 rounded-md"><Trash2 className="w-4 h-4" /></button></div></td></tr>))}</tbody></table></div>
        ) : (
          <div className="text-center py-12"><div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4"><Wallet className="w-10 h-10 text-gray-400" /></div><h3 className="text-lg font-medium text-gray-900 mb-2">No accounts found</h3><p className="text-gray-500">{searchTerm ? 'Try adjusting your search' : 'Create your first payment provider account'}</p></div>
        )}
      </div>
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"><div className="bg-white rounded-lg p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto"><div className="flex justify-between items-center mb-4"><h3 className="text-lg font-semibold text-gray-900">{editingAccount ? 'Edit Account' : 'Create Account'}</h3><button onClick={() => setShowModal(false)} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button></div>
          <form onSubmit={handleSubmit}><div className="space-y-4">
            <div><label className="block text-sm font-medium text-gray-700 mb-2">Payment Provider *</label><select value={formData.paymentProviderId} onChange={(e) => setFormData(prev => ({ ...prev, paymentProviderId: e.target.value }))} className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" required><option value="">Select a provider</option>{paymentProviders.map(provider => (<option key={provider.id} value={provider.id}>{provider.title}</option>))}</select></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-2">Account Name *</label><input type="text" value={formData.accountName} onChange={(e) => setFormData(prev => ({ ...prev, accountName: e.target.value }))} className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="e.g., ClassPedia Stripe Account" required /></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-2">Publishable Key *</label><input type="text" value={formData.publishableKey} onChange={(e) => setFormData(prev => ({ ...prev, publishableKey: e.target.value }))} className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="pk_test_..." required /></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-2">Secret Key *</label><div className="relative"><input type={showSecretKey ? "text" : "password"} value={formData.secretKey} onChange={(e) => setFormData(prev => ({ ...prev, secretKey: e.target.value }))} className="w-full px-3 py-2 pr-10 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="sk_test_..." required /><button type="button" onClick={() => setShowSecretKey(!showSecretKey)} className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600">{showSecretKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div></div>
            <div className="flex items-center space-x-6"><div className="flex items-center"><input type="checkbox" id="isActiveForPayment" checked={formData.isActiveForPayment === 1} onChange={(e) => setFormData(prev => ({ ...prev, isActiveForPayment: e.target.checked ? 1 : 0 }))} className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" /><label htmlFor="isActiveForPayment" className="ml-2 block text-sm text-gray-700">Active for Payment</label></div><div className="flex items-center"><input type="checkbox" id="isTestMode" checked={formData.isTestMode === 1} onChange={(e) => setFormData(prev => ({ ...prev, isTestMode: e.target.checked ? 1 : 0 }))} className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" /><label htmlFor="isTestMode" className="ml-2 block text-sm text-gray-700">Test Mode</label></div></div>
          </div><div className="flex justify-end space-x-3 mt-6"><button type="button" onClick={() => setShowModal(false)} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200">Cancel</button><button type="submit" disabled={submitting} className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50">{submitting ? <><div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>Processing...</> : <><Save className="w-4 h-4 mr-2" />{editingAccount ? 'Update' : 'Create'}</>}</button></div></form>
        </div></div>
      )}
    </AdminPageLayout>
  );
};

export default PaymentProviderAccounts;
