// API-related hooks
export { useAdmin } from './useAdmin';
export { useBadgeManagement } from './useBadgeManagement';
export { useCareerPath } from './useCareerPath';
export { useCareerPathDiscount } from './useCareerPathDiscount';
export { useCareerRoles } from './useCareerRoles';
export { useCareerSkills } from './useCareerSkills';
export { useCourseBadgeManagement } from './useCourseBadgeManagement';
export { useCourseSkillMapping } from './useCourseSkillMapping';
export { useDebounce } from '../utils/useDebounce';
export { useDiscountRateMapping } from './useDiscountRateMapping';
export { useDiscountRates } from './useDiscountRates';
export { useDynamicRoutes } from './useDynamicRoutes';
export { useEmailTemplates, useEmailTemplate, useEmailTemplateMutations } from './useEmailTemplates';
export { useLocalStorage } from '../utils/useLocalStorage';
export { useModalState } from '../utils/useModalState';
export { useReviews } from './useReviews';
export { useSlugManagement } from './useSlugManagement';
export { useToast } from '../utils/useToast';
export { useTopic } from './useTopic';
